language: php
php:
- 5.6
- 7.1
sudo: false
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=yousan@l2tp.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=yousan@l2tp.org
  - WP_VERSION=latest WP_MULTISITE=0
cache:
  directories:
  - node_modules
  - resources/vendor
  - "$HOME/.composer/cache"
install:
- nvm install 8
- npm install
- composer install
#before_script:
#- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
notifications:
  slack:
    rooms:
      secure: OItBgxkBQVMDBBDo9FkmLUtLe020t9Z30nw6oFx4inLBKzxuXT29pDcxfohnSPvoE1z0MQk6Mhxu+/IPuk9GA7L5/AbRaV8j0wQNl0adlcmCVoL0Mj1YN6GodXzYbPQqmm8rODbwWVNhaCJ1vfPfahWRFecnJVkeRb6rH8hN+xH+R9XQIj8yadvgxzUvhp++c6chhjws7R24Hj2khj7Xgz5su8w74qdxLKfrKt3DGaM+pvf9UNo8BghzN5D92A+rZwCHIFH+0GAD67psuifLG5uM+YD7OaC8CILUAJaK1BWLUiFTBNWH6mGaB51PdsLMGO9ZkaaV4GWh9OIdnS8sNotkLOiYmC8KeZg63ezUugU04gpvc+eZBqd4FX2RqEl5hXgDRPMgYsb3tgHBBEo46XKeDaYUuqDCFlBZhw5occEdQJooj5RxSQ8qO5EbPYz/RMhRfhrhJ8xsaYijuJUfDBb4HejhdDtr+PgR7hsV+kCzZe83VIrhJd9gaKEDwUrZZ4Q4rE62NxnNK1Bnt27Y3qGZ2hWB4Qo5+ZIKHk6wj3l0ZHnJD2+F4CzRprNhDTlCbiU8aljrSL60t6+5PNeH3yxZ5cWPXBChln5/8oRLxDolVnwc3hG7jqZw+cLaOKS7i6Egr3rw8SfIaz1b0tNiRmDDpEvilono0sJl4yHwyK4=
